version: '3'

services:
  mongodb:
    image: mongo
    container_name: ecommerce-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--replSet", "rs0"]
    restart: always

volumes:
  mongo-data: